export const BOARD_INIT = 'BOARD_INIT';
export const BOARD_MOUSE_DOWN = 'BOARD_MOUSE_DOWN';
export const BOARD_MOUSE_UP = 'BOARD_MOUSE_UP';
export const BOARD_MOUSE_LEAVE = 'BOARD_MOUSE_LEAVE';
export const BOARD_PLAY_POS = 'BOARD_PLAY_POS';